
# %%



# %% Industry codes from https://cps.ipums.org/cps-action/variables/ind1990#codes_section
# (json pulled out of the page source code)

inds = [
  {"id": 8857445, "label": "NIU", "indent": 0, "code": "000"},
  {"id": 8857691, "label": "AGRICULTURE, FORESTRY, AND FISHERIES", "indent": 0, "code": "null"},
  {"id": 8857446, "label": "Agricultural production, crops", "indent": 1, "code": "010"},
  {"id": 8857447, "label": "Agricultural production, livestock", "indent": 1, "code": "011"},
  {"id": 8857448, "label": "Veterinary services", "indent": 1, "code": "012"},
  {"id": 8857449, "label": "Landscape and horticultural services", "indent": 1, "code": "020"},
  {"id": 8857450, "label": "Agricultural services, n.e.c.", "indent": 1, "code": "030"},
  {"id": 8857451, "label": "Forestry", "indent": 1, "code": "031"},
  {"id": 8857452, "label": "Fishing, hunting, and trapping", "indent": 1, "code": "032"},
  {"id": 8857692, "label": "MINING", "indent": 0, "code": "null"},
  {"id": 8857453, "label": "Metal mining", "indent": 1, "code": "040"},
  {"id": 8857454, "label": "Coal mining", "indent": 1, "code": "041"},
  {"id": 8857455, "label": "Oil and gas extraction", "indent": 1, "code": "042"},
  {"id": 8857456, "label": "Nonmetallic mining and quarrying, except fuels", "indent": 1, "code": "050"},
  {"id": 8857693, "label": "CONSTRUCTION", "indent": 0, "code": "null"},
  {"id": 8857457, "label": "All construction", "indent": 1, "code": "060"},
  {"id": 8857694, "label": "MANUFACTURING", "indent": 0, "code": "null"},
  {"id": 8857695, "label": "Nondurable Goods", "indent": 1, "code": "null"},
  {"id": 8857696, "label": "Food and kindred products:", "indent": 2, "code": "null"},
  {"id": 8857458, "label": "Meat products", "indent": 3, "code": "100"},
  {"id": 8857459, "label": "Dairy products", "indent": 3, "code": "101"},
  {"id": 8857460, "label": "Canned, frozen, and preserved fruits and vegetables", "indent": 3, "code": "102"},
  {"id": 8857461, "label": "Grain mill products", "indent": 3, "code": "110"},
  {"id": 8857462, "label": "Bakery products", "indent": 3, "code": "111"},
  {"id": 8857463, "label": "Sugar and confectionery products", "indent": 3, "code": "112"},
  {"id": 8857464, "label": "Beverage industries", "indent": 3, "code": "120"},
  {"id": 8857465, "label": "Misc. food preparations and kindred products", "indent": 3, "code": "121"},
  {"id": 8857466, "label": "Food industries, n.s.", "indent": 3, "code": "122"},
  {"id": 8857467, "label": "Tobacco manufactures", "indent": 2, "code": "130"},
  {"id": 8857697, "label": "Textile mill products:", "indent": 2, "code": "null"},
  {"id": 8857468, "label": "Knitting mills", "indent": 3, "code": "132"},
  {"id": 8857469, "label": "Dyeing and finishing textiles, except wool and knit goods", "indent": 3, "code": "140"},
  {"id": 8857470, "label": "Carpets and rugs", "indent": 3, "code": "141"},
  {"id": 8857471, "label": "Yarn, thread, and fabric mills", "indent": 3, "code": "142"},
  {"id": 8857472, "label": "Miscellaneous textile mill products", "indent": 3, "code": "150"},
  {"id": 8857698, "label": "Apparel and other finished textile products:", "indent": 2, "code": "null"},
  {"id": 8857473, "label": "Apparel and accessories, except knit", "indent": 3, "code": "151"},
  {"id": 8857474, "label": "Miscellaneous fabricated textile products", "indent": 3, "code": "152"},
  {"id": 8857699, "label": "Paper and allied products:", "indent": 2, "code": "null"},
  {"id": 8857475, "label": "Pulp, paper, and paperboard mills", "indent": 3, "code": "160"},
  {"id": 8857476, "label": "Miscellaneous paper and pulp products", "indent": 3, "code": "161"},
  {"id": 8857477, "label": "Paperboard containers and boxes", "indent": 3, "code": "162"},
  {"id": 8857700, "label": "Printing, publishing, and allied industries:", "indent": 2, "code": "null"},
  {"id": 8857478, "label": "Newspaper publishing and printing", "indent": 3, "code": "171"},
  {"id": 8857479, "label": "Printing, publishing, and allied industries, except newspapers", "indent": 3, "code": "172"},
  {"id": 8857701, "label": "Chemicals and allied products:", "indent": 2, "code": "null"},
  {"id": 8857480, "label": "Plastics, synthetics, and resins", "indent": 3, "code": "180"},
  {"id": 8857481, "label": "Drugs", "indent": 3, "code": "181"},
  {"id": 8857482, "label": "Soaps and cosmetics", "indent": 3, "code": "182"},
  {"id": 8857483, "label": "Paints, varnishes, and related products", "indent": 3, "code": "190"},
  {"id": 8857484, "label": "Agricultural chemicals", "indent": 3, "code": "191"},
  {"id": 8857485, "label": "Industrial and miscellaneous chemicals", "indent": 3, "code": "192"},
  {"id": 8857702, "label": "Petroleum and coal products:", "indent": 2, "code": "null"},
  {"id": 8857486, "label": "Petroleum refining", "indent": 3, "code": "200"},
  {"id": 8857487, "label": "Miscellaneous petroleum and coal products", "indent": 3, "code": "201"},
  {"id": 8857703, "label": "Rubber and miscellaneous plastics products:", "indent": 2, "code": "null"},
  {"id": 8857488, "label": "Tires and inner tubes", "indent": 3, "code": "210"},
  {"id": 8857489, "label": "Other rubber products, and plastics footwear and belting", "indent": 3, "code": "211"},
  {"id": 8857490, "label": "Miscellaneous plastics products", "indent": 3, "code": "212"},
  {"id": 8857704, "label": "Leather and leather products:", "indent": 2, "code": "null"},
  {"id": 8857491, "label": "Leather tanning and finishing", "indent": 3, "code": "220"},
  {"id": 8857492, "label": "Footwear, except rubber and plastic", "indent": 3, "code": "221"},
  {"id": 8857493, "label": "Leather products, except footwear", "indent": 3, "code": "222"},
  #{"id": 8857494, "label": "Manufacturing, non-durable - allocated", "indent": 0, "code": "229"},
  {"id": 8857705, "label": "Durable Goods", "indent": 1, "code": "null"},
  {"id": 8857706, "label": "Lumber and woods products, except furniture:", "indent": 2, "code": "null"},
  {"id": 8857495, "label": "Logging", "indent": 3, "code": "230"},
  {"id": 8857496, "label": "Sawmills, planing mills, and millwork", "indent": 3, "code": "231"},
  {"id": 8857497, "label": "Wood buildings and mobile homes", "indent": 3, "code": "232"},
  {"id": 8857498, "label": "Miscellaneous wood products", "indent": 3, "code": "241"},
  {"id": 8857499, "label": "Furniture and fixtures", "indent": 2, "code": "242"},
  {"id": 8857707, "label": "Stone, clay, glass and concrete products:", "indent": 2, "code": "null"},
  {"id": 8857500, "label": "Glass and glass products", "indent": 3, "code": "250"},
  {"id": 8857501, "label": "Cement, concrete, gypsum, and plaster products", "indent": 3, "code": "251"},
  {"id": 8857502, "label": "Structural clay products", "indent": 3, "code": "252"},
  {"id": 8857503, "label": "Pottery and related products", "indent": 3, "code": "261"},
  {"id": 8857504, "label": "Misc. nonmetallic mineral and stone products", "indent": 3, "code": "262"},
  {"id": 8857708, "label": "Metal industries:", "indent": 2, "code": "null"},
  {"id": 8857505, "label": "Blast furnaces, steelworks, rolling and finishing mills", "indent": 3, "code": "270"},
  {"id": 8857506, "label": "Iron and steel foundries", "indent": 3, "code": "271"},
  {"id": 8857507, "label": "Primary aluminum industries", "indent": 3, "code": "272"},
  {"id": 8857508, "label": "Other primary metal industries", "indent": 3, "code": "280"},
  {"id": 8857509, "label": "Cutlery, handtools, and general hardware", "indent": 3, "code": "281"},
  {"id": 8857510, "label": "Fabricated structural metal products", "indent": 3, "code": "282"},
  {"id": 8857511, "label": "Screw machine products", "indent": 3, "code": "290"},
  {"id": 8857512, "label": "Metal forgings and stampings", "indent": 3, "code": "291"},
  {"id": 8857513, "label": "Ordnance", "indent": 3, "code": "292"},
  {"id": 8857514, "label": "Miscellaneous fabricated metal products", "indent": 3, "code": "300"},
  {"id": 8857515, "label": "Metal industries, n.s.", "indent": 3, "code": "301"},
  {"id": 8857709, "label": "Machinery and computing equipment:", "indent": 2, "code": "null"},
  {"id": 8857516, "label": "Engines and turbines", "indent": 3, "code": "310"},
  {"id": 8857517, "label": "Farm machinery and equipment", "indent": 3, "code": "311"},
  {"id": 8857518, "label": "Construction and material handling machines", "indent": 3, "code": "312"},
  {"id": 8857519, "label": "Metalworking machinery", "indent": 3, "code": "320"},
  {"id": 8857520, "label": "Office and accounting machines", "indent": 3, "code": "321"},
  {"id": 8857521, "label": "Computers and related equipment", "indent": 3, "code": "322"},
  {"id": 8857522, "label": "Machinery, except electrical, n.e.c.", "indent": 3, "code": "331"},
  {"id": 8857523, "label": "Machinery, n.s.", "indent": 3, "code": "332"},
  {"id": 8857710, "label": "Electrical machinery, equipment, and supplies:", "indent": 2, "code": "null"},
  {"id": 8857524, "label": "Household appliances", "indent": 3, "code": "340"},
  {"id": 8857525, "label": "Radio, TV, and communication equipment", "indent": 3, "code": "341"},
  {"id": 8857526, "label": "Electrical machinery, equipment, and supplies, n.e.c.", "indent": 3, "code": "342"},
  {"id": 8857527, "label": "Electrical machinery, equipment, and supplies, n.s.", "indent": 3, "code": "350"},
  {"id": 8857711, "label": "Transportation equipment:", "indent": 2, "code": "null"},
  {"id": 8857528, "label": "Motor vehicles and motor vehicle equipment", "indent": 3, "code": "351"},
  {"id": 8857529, "label": "Aircraft and parts", "indent": 3, "code": "352"},
  {"id": 8857530, "label": "Ship and boat building and repairing", "indent": 3, "code": "360"},
  {"id": 8857531, "label": "Railroad locomotives and equipment", "indent": 3, "code": "361"},
  {"id": 8857532, "label": "Guided missiles, space vehicles, and parts", "indent": 3, "code": "362"},
  {"id": 8857533, "label": "Cycles and miscellaneous transportation equipment", "indent": 3, "code": "370"},
  {"id": 8857712, "label": "Professional and photographic equipment, and watches:", "indent": 2, "code": "null"},
  {"id": 8857534, "label": "Scientific and controlling instruments", "indent": 3, "code": "371"},
  {"id": 8857535, "label": "Medical, dental, and optical instruments and supplies", "indent": 3, "code": "372"},
  {"id": 8857536, "label": "Photographic equipment and supplies", "indent": 3, "code": "380"},
  {"id": 8857537, "label": "Watches, clocks, and clockwork operated devices", "indent": 3, "code": "381"},
  {"id": 8857538, "label": "Toys, amusement, and sporting goods", "indent": 2, "code": "390"},
  {"id": 8857539, "label": "Miscellaneous manufacturing industries", "indent": 2, "code": "391"},
  {"id": 8857540, "label": "Manufacturing industries, n.s.", "indent": 2, "code": "392"},
  {"id": 8857713, "label": "TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES", "indent": 0, "code": "null"},
  {"id": 8857714, "label": "Transportation:", "indent": 1, "code": "null"},
  {"id": 8857541, "label": "Railroads", "indent": 2, "code": "400"},
  {"id": 8857542, "label": "Bus service and urban transit", "indent": 2, "code": "401"},
  {"id": 8857543, "label": "Taxicab service", "indent": 2, "code": "402"},
  {"id": 8857544, "label": "Trucking service", "indent": 2, "code": "410"},
  {"id": 8857545, "label": "Warehousing and storage", "indent": 2, "code": "411"},
  {"id": 8857546, "label": "U.S. Postal Service", "indent": 2, "code": "412"},
  {"id": 8857547, "label": "Water transportation", "indent": 2, "code": "420"},
  {"id": 8857548, "label": "Air transportation", "indent": 2, "code": "421"},
  {"id": 8857549, "label": "Pipe lines, except natural gas", "indent": 2, "code": "422"},
  {"id": 8857550, "label": "Services incidental to transportation", "indent": 2, "code": "432"},
  {"id": 8857715, "label": "Communications:", "indent": 1, "code": "null"},
  {"id": 8857551, "label": "Radio and television broadcasting and cable", "indent": 2, "code": "440"},
  {"id": 8857552, "label": "Wired communications", "indent": 2, "code": "441"},
  {"id": 8857553, "label": "Telegraph and miscellaneous communications services", "indent": 2, "code": "442"},
  {"id": 8857716, "label": "Utilities and sanitary services:", "indent": 1, "code": "null"},
  {"id": 8857554, "label": "Electric light and power", "indent": 2, "code": "450"},
  {"id": 8857555, "label": "Gas and steam supply systems", "indent": 2, "code": "451"},
  {"id": 8857556, "label": "Electric and gas, and other combinations", "indent": 2, "code": "452"},
  {"id": 8857557, "label": "Water supply and irrigation", "indent": 2, "code": "470"},
  {"id": 8857558, "label": "Sanitary services", "indent": 2, "code": "471"},
  {"id": 8857559, "label": "Utilities, n.s.", "indent": 2, "code": "472"},
  {"id": 8857717, "label": "WHOLESALE TRADE", "indent": 0, "code": "null"},
  {"id": 8857718, "label": "Durable Goods:", "indent": 1, "code": "null"},
  {"id": 8857560, "label": "Motor vehicles and equipment", "indent": 2, "code": "500"},
  {"id": 8857561, "label": "Furniture and home furnishings", "indent": 2, "code": "501"},
  {"id": 8857562, "label": "Lumber and construction materials", "indent": 2, "code": "502"},
  {"id": 8857563, "label": "Professional and commercial equipment and supplies", "indent": 2, "code": "510"},
  {"id": 8857564, "label": "Metals and minerals, except petroleum", "indent": 2, "code": "511"},
  {"id": 8857565, "label": "Electrical goods", "indent": 2, "code": "512"},
  {"id": 8857566, "label": "Hardware, plumbing and heating supplies", "indent": 2, "code": "521"},
  {"id": 8857567, "label": "Machinery, equipment, and supplies", "indent": 2, "code": "530"},
  {"id": 8857568, "label": "Scrap and waste materials", "indent": 2, "code": "531"},
  {"id": 8857569, "label": "Miscellaneous wholesale, durable goods", "indent": 2, "code": "532"},
  {"id": 8857719, "label": "Nondurable Goods:", "indent": 1, "code": "null"},
  {"id": 8857570, "label": "Paper and paper products", "indent": 2, "code": "540"},
  {"id": 8857571, "label": "Drugs, chemicals, and allied products", "indent": 2, "code": "541"},
  {"id": 8857572, "label": "Apparel, fabrics, and notions", "indent": 2, "code": "542"},
  {"id": 8857573, "label": "Groceries and related products", "indent": 2, "code": "550"},
  {"id": 8857574, "label": "Farm-product raw materials", "indent": 2, "code": "551"},
  {"id": 8857575, "label": "Petroleum products", "indent": 2, "code": "552"},
  {"id": 8857576, "label": "Alcoholic beverages", "indent": 2, "code": "560"},
  {"id": 8857577, "label": "Farm supplies", "indent": 2, "code": "561"},
  {"id": 8857578, "label": "Miscellaneous wholesale, nondurable goods", "indent": 2, "code": "562"},
  {"id": 8857579, "label": "Wholesale trade, n.s.", "indent": 2, "code": "571"},
  {"id": 8857720, "label": "RETAIL TRADE", "indent": 0, "code": "null"},
  {"id": 8857580, "label": "Lumber and building material retailing", "indent": 1, "code": "580"},
  {"id": 8857581, "label": "Hardware stores", "indent": 1, "code": "581"},
  {"id": 8857582, "label": "Retail nurseries and garden stores", "indent": 1, "code": "582"},
  {"id": 8857583, "label": "Mobile home dealers", "indent": 1, "code": "590"},
  {"id": 8857584, "label": "Department stores", "indent": 1, "code": "591"},
  {"id": 8857585, "label": "Variety stores", "indent": 1, "code": "592"},
  {"id": 8857586, "label": "Miscellaneous general merchandise stores", "indent": 1, "code": "600"},
  {"id": 8857587, "label": "Grocery stores", "indent": 1, "code": "601"},
  {"id": 8857588, "label": "Dairy products stores", "indent": 1, "code": "602"},
  {"id": 8857589, "label": "Retail bakeries", "indent": 1, "code": "610"},
  {"id": 8857590, "label": "Food stores, n.e.c.", "indent": 1, "code": "611"},
  {"id": 8857591, "label": "Motor vehicle dealers", "indent": 1, "code": "612"},
  {"id": 8857592, "label": "Auto and home supply stores", "indent": 1, "code": "620"},
  {"id": 8857593, "label": "Gasoline service stations", "indent": 1, "code": "621"},
  {"id": 8857594, "label": "Miscellaneous vehicle dealers", "indent": 1, "code": "622"},
  {"id": 8857595, "label": "Apparel and accessory stores, except shoe", "indent": 1, "code": "623"},
  {"id": 8857596, "label": "Shoe stores", "indent": 1, "code": "630"},
  {"id": 8857597, "label": "Furniture and home furnishings stores", "indent": 1, "code": "631"},
  {"id": 8857598, "label": "Household appliance stores", "indent": 1, "code": "632"},
  {"id": 8857599, "label": "Radio, TV, and computer stores", "indent": 1, "code": "633"},
  {"id": 8857600, "label": "Music stores", "indent": 1, "code": "640"},
  {"id": 8857601, "label": "Eating and drinking places", "indent": 1, "code": "641"},
  {"id": 8857602, "label": "Drug stores", "indent": 1, "code": "642"},
  {"id": 8857603, "label": "Liquor stores", "indent": 1, "code": "650"},
  {"id": 8857604, "label": "Sporting goods, bicycles, and hobby stores", "indent": 1, "code": "651"},
  {"id": 8857605, "label": "Book and stationery stores", "indent": 1, "code": "652"},
  {"id": 8857606, "label": "Jewelry stores", "indent": 1, "code": "660"},
  {"id": 8857607, "label": "Gift, novelty, and souvenir shops", "indent": 1, "code": "661"},
  {"id": 8857608, "label": "Sewing, needlework, and piece goods stores", "indent": 1, "code": "662"},
  {"id": 8857609, "label": "Catalog and mail order houses", "indent": 1, "code": "663"},
  {"id": 8857610, "label": "Vending machine operators", "indent": 1, "code": "670"},
  {"id": 8857611, "label": "Direct selling establishments", "indent": 1, "code": "671"},
  {"id": 8857612, "label": "Fuel dealers", "indent": 1, "code": "672"},
  {"id": 8857613, "label": "Retail florists", "indent": 1, "code": "681"},
  {"id": 8857614, "label": "Miscellaneous retail stores", "indent": 1, "code": "682"},
  {"id": 8857615, "label": "Retail trade, n.s.", "indent": 1, "code": "691"},
  {"id": 8857721, "label": "FINANCE, INSURANCE, AND REAL ESTATE", "indent": 0, "code": "null"},
  {"id": 8857616, "label": "Banking", "indent": 1, "code": "700"},
  {"id": 8857617, "label": "Savings institutions, including credit unions", "indent": 1, "code": "701"},
  {"id": 8857618, "label": "Credit agencies, n.e.c.", "indent": 1, "code": "702"},
  {"id": 8857619, "label": "Security, commodity brokerage, and investment companies", "indent": 1, "code": "710"},
  {"id": 8857620, "label": "Insurance", "indent": 1, "code": "711"},
  {"id": 8857621, "label": "Real estate, including real estate-insurance offices", "indent": 1, "code": "712"},
  {"id": 8857722, "label": "BUSINESS AND REPAIR SERVICES", "indent": 0, "code": "null"},
  {"id": 8857622, "label": "Advertising", "indent": 1, "code": "721"},
  {"id": 8857623, "label": "Services to dwellings and other buildings", "indent": 1, "code": "722"},
  {"id": 8857624, "label": "Personnel supply services", "indent": 1, "code": "731"},
  {"id": 8857625, "label": "Computer and data processing services", "indent": 1, "code": "732"},
  {"id": 8857626, "label": "Detective and protective services", "indent": 1, "code": "740"},
  {"id": 8857627, "label": "Business services, n.e.c.", "indent": 1, "code": "741"},
  {"id": 8857628, "label": "Automotive rental and leasing, without drivers", "indent": 1, "code": "742"},
  {"id": 8857629, "label": "Automobile parking and carwashes", "indent": 1, "code": "750"},
  {"id": 8857630, "label": "Automotive repair and related services", "indent": 1, "code": "751"},
  {"id": 8857631, "label": "Electrical repair shops", "indent": 1, "code": "752"},
  {"id": 8857632, "label": "Miscellaneous repair services", "indent": 1, "code": "760"},
  {"id": 8857723, "label": "PERSONAL SERVICES", "indent": 0, "code": "null"},
  {"id": 8857633, "label": "Private households", "indent": 1, "code": "761"},
  {"id": 8857634, "label": "Hotels and motels", "indent": 1, "code": "762"},
  {"id": 8857635, "label": "Lodging places, except hotels and motels", "indent": 1, "code": "770"},
  {"id": 8857636, "label": "Laundry, cleaning, and garment services", "indent": 1, "code": "771"},
  {"id": 8857637, "label": "Beauty shops", "indent": 1, "code": "772"},
  {"id": 8857638, "label": "Barber shops", "indent": 1, "code": "780"},
  {"id": 8857639, "label": "Funeral service and crematories", "indent": 1, "code": "781"},
  {"id": 8857640, "label": "Shoe repair shops", "indent": 1, "code": "782"},
  {"id": 8857641, "label": "Dressmaking shops", "indent": 1, "code": "790"},
  {"id": 8857642, "label": "Miscellaneous personal services", "indent": 1, "code": "791"},
  {"id": 8857724, "label": "ENTERTAINMENT AND RECREATION SERVICES", "indent": 0, "code": "null"},
  {"id": 8857643, "label": "Theaters and motion pictures", "indent": 1, "code": "800"},
  {"id": 8857644, "label": "Video tape rental", "indent": 1, "code": "801"},
  {"id": 8857645, "label": "Bowling centers", "indent": 1, "code": "802"},
  {"id": 8857646, "label": "Miscellaneous entertainment and recreation services", "indent": 1, "code": "810"},
  {"id": 8857725, "label": "PROFESSIONAL AND RELATED SERVICES", "indent": 0, "code": "null"},
  {"id": 8857647, "label": "Offices and clinics of physicians", "indent": 1, "code": "812"},
  {"id": 8857648, "label": "Offices and clinics of dentists", "indent": 1, "code": "820"},
  {"id": 8857649, "label": "Offices and clinics of chiropractors", "indent": 1, "code": "821"},
  {"id": 8857650, "label": "Offices and clinics of optometrists", "indent": 1, "code": "822"},
  {"id": 8857651, "label": "Offices and clinics of health practitioners, n.e.c.", "indent": 1, "code": "830"},
  {"id": 8857652, "label": "Hospitals", "indent": 1, "code": "831"},
  {"id": 8857653, "label": "Nursing and personal care facilities", "indent": 1, "code": "832"},
  {"id": 8857654, "label": "Health services, n.e.c.", "indent": 1, "code": "840"},
  {"id": 8857655, "label": "Legal services", "indent": 1, "code": "841"},
  {"id": 8857656, "label": "Elementary and secondary schools", "indent": 1, "code": "842"},
  {"id": 8857657, "label": "Colleges and universities", "indent": 1, "code": "850"},
  {"id": 8857658, "label": "Vocational schools", "indent": 1, "code": "851"},
  {"id": 8857659, "label": "Libraries", "indent": 1, "code": "852"},
  {"id": 8857660, "label": "Educational services, n.e.c.", "indent": 1, "code": "860"},
  {"id": 8857661, "label": "Job training and vocational rehabilitation services", "indent": 1, "code": "861"},
  {"id": 8857662, "label": "Child day care services", "indent": 1, "code": "862"},
  {"id": 8857663, "label": "Family child care homes", "indent": 1, "code": "863"},
  {"id": 8857664, "label": "Residential care facilities, without nursing", "indent": 1, "code": "870"},
  {"id": 8857665, "label": "Social services, n.e.c.", "indent": 1, "code": "871"},
  {"id": 8857666, "label": "Museums, art galleries, and zoos", "indent": 1, "code": "872"},
  {"id": 8857667, "label": "Labor unions", "indent": 1, "code": "873"},
  {"id": 8857668, "label": "Religious organizations", "indent": 1, "code": "880"},
  {"id": 8857669, "label": "Membership organizations, n.e.c.", "indent": 1, "code": "881"},
  {"id": 8857670, "label": "Engineering, architectural, and surveying services", "indent": 1, "code": "882"},
  {"id": 8857671, "label": "Accounting, auditing, and bookkeeping services", "indent": 1, "code": "890"},
  {"id": 8857672, "label": "Research, development, and testing services", "indent": 1, "code": "891"},
  {"id": 8857673, "label": "Management and public relations services", "indent": 1, "code": "892"},
  {"id": 8857674, "label": "Miscellaneous professional and related services", "indent": 1, "code": "893"},
  {"id": 8857726, "label": "PUBLIC ADMINISTRATION", "indent": 0, "code": "null"},
  {"id": 8857675, "label": "Executive and legislative offices", "indent": 1, "code": "900"},
  {"id": 8857676, "label": "General government, n.e.c.", "indent": 1, "code": "901"},
  {"id": 8857677, "label": "Justice, public order, and safety", "indent": 1, "code": "910"},
  {"id": 8857678, "label": "Public finance, taxation, and monetary policy", "indent": 1, "code": "921"},
  {"id": 8857679, "label": "Administration of human resources programs", "indent": 1, "code": "922"},
  {"id": 8857680, "label": "Administration of environmental quality and housing programs", "indent": 1, "code": "930"},
  {"id": 8857681, "label": "Administration of economic programs", "indent": 1, "code": "931"},
  {"id": 8857682, "label": "National security and international affairs", "indent": 1, "code": "932"},
  {"id": 8857727, "label": "ACTIVE DUTY MILITARY", "indent": 0, "code": "null"},
  {"id": 8857728, "label": "Armed Forces:", "indent": 1, "code": "null"},
  {"id": 8857683, "label": "Army", "indent": 2, "code": "940"},
  {"id": 8857684, "label": "Air Force", "indent": 2, "code": "941"},
  {"id": 8857685, "label": "Navy", "indent": 2, "code": "942"},
  {"id": 8857686, "label": "Marines", "indent": 2, "code": "950"},
  {"id": 8857687, "label": "Coast Guard", "indent": 2, "code": "951"},
  {"id": 8857688, "label": "Armed Forces, branch not specified", "indent": 2, "code": "952"},
  {"id": 8857689, "label": "Military Reserves or National Guard", "indent": 2, "code": "960"},
  {"id": 8857690, "label": "Unknown", "indent": 0, "code": "998",
  }
]


# %% IND 1990 VALUE COUNTS
# parsed from the training data
IND1990_VALUECOUNTS = {'All construction': 23151,
 'Elementary and secondary schools': 22433,
 'Hospitals': 14376,
 'Eating and drinking places': 13078,
 'NIU': 11386,
 'Health services, n.e.c.': 9443,
 'Colleges and universities': 8083,
 'Justice, public order, and safety': 6480,
 'Insurance': 6232,
 'Trucking service': 5505,
 'Grocery stores': 5280,
 'Computer and data processing services': 5189,
 'Miscellaneous entertainment and recreation services': 5169,
 'Banking': 5025,
 'Real estate, including real estate-insurance offices': 4959,
 'Department stores': 4440,
 'Business services, n.e.c.': 4312,
 'Nursing and personal care facilities': 3936,
 'Legal services': 3792,
 'Engineering, architectural, and surveying services': 3661,
 'Social services, n.e.c.': 3587,
 'Child day care services': 3573,
 'Offices and clinics of physicians': 3418,
 'Hotels and motels': 3000,
 'Security, commodity brokerage, and investment companies': 2962,
 'Services to dwellings and other buildings': 2928,
 'Management and public relations services': 2925,
 'Automotive repair and related services': 2723,
 'Motor vehicle dealers': 2660,
 'Agricultural production, crops': 2622,
 'Electrical machinery, equipment, and supplies, n.e.c.': 2535,
 'Administration of human resources programs': 2518,
 'Landscape and horticultural services': 2484,
 'Motor vehicles and motor vehicle equipment': 2398,
 'Executive and legislative offices': 2351,
 'Agricultural production, livestock': 2339,
 'Services incidental to transportation': 2305,
 'Personnel supply services': 2267,
 'Accounting, auditing, and bookkeeping services': 2267,
 'Printing, publishing, and allied industries, except newspapers': 2142,
 'Religious organizations': 2113,
 'Lumber and building material retailing': 2050,
 'Membership organizations, n.e.c.': 2041,
 'Miscellaneous retail stores': 2024,
 'National security and international affairs': 2010,
 'Offices and clinics of dentists': 1983,
 'Beauty shops': 1972,
 'Groceries and related products': 1949,
 'Credit agencies, n.e.c.': 1942,
 'U.S. Postal Service': 1865,
 'Administration of economic programs': 1788,
 'Drug stores': 1728,
 'Electric light and power': 1706,
 'Machinery, except electrical, n.e.c.': 1645,
 'Wired communications': 1641,
 'Apparel and accessory stores, except shoe': 1631,
 'Educational services, n.e.c.': 1598,
 'Residential care facilities, without nursing': 1591,
 'Armed Forces, branch not specified': 1566,
 'Oil and gas extraction': 1539,
 'Detective and protective services': 1513,
 'Miscellaneous personal services': 1498,
 'Sanitary services': 1460,
 'Radio and television broadcasting and cable': 1423,
 'Private households': 1395,
 'Medical, dental, and optical instruments and supplies': 1394,
 'Research, development, and testing services': 1311,
 'Plastics, synthetics, and resins': 1246,
 'Air transportation': 1225,
 'Meat products': 1159,
 'Furniture and fixtures': 1131,
 'Furniture and home furnishings stores': 1122,
 'Advertising': 1116,
 'Drugs': 1115,
 'Miscellaneous manufacturing industries': 1111,
 'Miscellaneous repair services': 1106,
 'Auto and home supply stores': 1067,
 'Aircraft and parts': 1067,
 'Bus service and urban transit': 1046,
 'Radio, TV, and computer stores': 1026,
 'Industrial and miscellaneous chemicals': 996,
 'Gasoline service stations': 987,
 'Public finance, taxation, and monetary policy': 983,
 'Miscellaneous general merchandise stores': 981,
 'Machinery, equipment, and supplies': 980,
 'Administration of environmental quality and housing programs': 972,
 'Sporting goods, bicycles, and hobby stores': 957,
 'Guided missiles, space vehicles, and parts': 927,
 'Fabricated structural metal products': 889,
 'Telegraph and miscellaneous communications services': 875,
 'Miscellaneous fabricated metal products': 859,
 'Museums, art galleries, and zoos': 829,
 'Newspaper publishing and printing': 769,
 'Professional and commercial equipment and supplies': 767,
 'Theaters and motion pictures': 756,
 'Warehousing and storage': 738,
 'Retail nurseries and garden stores': 724,
 'Railroads': 722,
 'Computers and related equipment': 688,
 'Savings institutions, including credit unions': 681,
 'Screw machine products': 676,
 'Book and stationery stores': 664,
 'Laundry, cleaning, and garment services': 653,
 'Blast furnaces, steelworks, rolling and finishing mills': 629,
 'Veterinary services': 613,
 'Water supply and irrigation': 596,
 'Offices and clinics of health practitioners, n.e.c.': 568,
 'Catalog and mail order houses': 559,
 'Miscellaneous wood products': 558,
 'Drugs, chemicals, and allied products': 558,
 'Scientific and controlling instruments': 550,
 'Beverage industries': 540,
 'Libraries': 533,
 'Apparel and accessories, except knit': 523,
 'Hardware stores': 517,
 'Pulp, paper, and paperboard mills': 513,
 'Direct selling establishments': 507,
 'Electrical goods': 505,
 'Coal mining': 498,
 'Taxicab service': 492,
 'Food stores, n.e.c.': 490,
 'Miscellaneous wholesale, durable goods': 490,
 'Retail trade, n.s.': 460,
 'Ship and boat building and repairing': 458,
 'Bakery products': 440,
 'Retail bakeries': 433,
 'Jewelry stores': 432,
 'Misc. food preparations and kindred products': 432,
 'Petroleum refining': 419,
 'Dairy products': 414,
 'Sawmills, planing mills, and millwork': 414,
 'Miscellaneous wholesale, nondurable goods': 412,
 'Grain mill products': 409,
 'Job training and vocational rehabilitation services': 399,
 'Lumber and construction materials': 399,
 'Canned, frozen, and preserved fruits and vegetables': 395,
 'Cement, concrete, gypsum, and plaster products': 394,
 'Construction and material handling machines': 387,
 'Motor vehicles and equipment': 384,
 'Electrical repair shops': 383,
 'Farm machinery and equipment': 377,
 'Hardware, plumbing and heating supplies': 366,
 'Radio, TV, and communication equipment': 364,
 'General government, n.e.c.': 355,
 'Gift, novelty, and souvenir shops': 353,
 'Miscellaneous vehicle dealers': 350,
 'Metalworking machinery': 346,
 'Petroleum products': 346,
 'Manufacturing industries, n.s.': 333,
 'Automotive rental and leasing, without drivers': 332,
 'Glass and glass products': 330,
 'Nonmetallic mining and quarrying, except fuels': 314,
 'Offices and clinics of chiropractors': 307,
 'Liquor stores': 307,
 'Alcoholic beverages': 302,
 'Offices and clinics of optometrists': 302,
 'Fuel dealers': 301,
 'Toys, amusement, and sporting goods': 297,
 'Soaps and cosmetics': 293,
 'Logging': 289,
 'Gas and steam supply systems': 283,
 'Yarn, thread, and fabric mills': 278,
 'Automobile parking and carwashes': 272,
 'Machinery, n.s.': 270,
 'Scrap and waste materials': 258,
 'Miscellaneous paper and pulp products': 252,
 'Retail florists': 248,
 'Funeral service and crematories': 247,
 'Apparel, fabrics, and notions': 225,
 'Farm-product raw materials': 224,
 'Shoe stores': 222,
 'Vocational schools': 215,
 'Electric and gas, and other combinations': 208,
 'Fishing, hunting, and trapping': 203,
 'Lodging places, except hotels and motels': 195,
 'Barber shops': 195,
 'Miscellaneous textile mill products': 192,
 'Paperboard containers and boxes': 191,
 'Sugar and confectionery products': 189,
 'Iron and steel foundries': 184,
 'Labor unions': 184,
 'Misc. nonmetallic mineral and stone products': 182,
 'Household appliances': 171,
 'Other rubber products, and plastics footwear and belting': 170,
 'Sewing, needlework, and piece goods stores': 167,
 'Paper and paper products': 167,
 'Household appliance stores': 164,
 'Water transportation': 162,
 'Furniture and home furnishings': 153,
 'Metal mining': 149,
 'Forestry': 149,
 'Primary aluminum industries': 148,
 'Tires and inner tubes': 148,
 'Engines and turbines': 145,
 'Pipe lines, except natural gas': 139,
 'Paints, varnishes, and related products': 138,
 'Metals and minerals, except petroleum': 135,
 'Other primary metal industries': 134,
 'Music stores': 127,
 'Farm supplies': 121,
 'Ordnance': 117,
 'Metal forgings and stampings': 111,
 'Cutlery, handtools, and general hardware': 109,
 'Vending machine operators': 107,
 'Cycles and miscellaneous transportation equipment': 96,
 'Food industries, n.s.': 95,
 'Bowling centers': 93,
 'Agricultural chemicals': 92,
 'Carpets and rugs': 90,
 'Structural clay products': 81,
 'Video tape rental': 73,
 'Pottery and related products': 72,
 'Wood buildings and mobile homes': 72,
 'Footwear, except rubber and plastic': 71,
 'Leather tanning and finishing': 64,
 'Knitting mills': 63,
 'Railroad locomotives and equipment': 60,
 'Utilities, n.s.': 57,
 'Dyeing and finishing textiles, except wool and knit goods': 55,
 'Tobacco manufactures': 51,
 'Metal industries, n.s.': 47,
 'Miscellaneous petroleum and coal products': 44,
 'Shoe repair shops': 3}






#%% I used this code to generate the dictionary for the industry groups.

from collections import defaultdict, Counter
'''
headersets = defaultdict(set)
def headerstocat(headerlist):
    return tuple(headerlist)
headers = [None,None,None,None]
for ind in inds:
    label, indent, code = ind['label'],ind['indent'],ind['code']
    # Close out previous headers
    for x in range(indent,3):
            headers[x] = None
    if code == "null":
        # Create new header
        headers[indent] = label
        #print(label)
        #print(headers)
    else:
        # add category to the appropriate sets
        validheaders = [header for header in headers if header != None]
        for header in validheaders:
            headersets[header].add(label)
INDUSTRYDICT = dict()
# check to see if any industry categories are singular
# If they are, I don't want to add them, because they would be redundant 
for k,v in headersets.items():
    numberofsubcatsindata = len([cat for cat in v if cat in IND1990_VALUECOUNTS.keys()])
    if numberofsubcatsindata <= 1:
        #print("Not enough subcategories in ",k)
        INDUSTRYDICT[k] = frozenset(v)
        continue
    else:
        INDUSTRYDICT[k] = frozenset(v)
        continue
'''




# %% Hardcode the above computed material

INDUSTRYGROUPS = {
    'AGRICULTURE, FORESTRY, AND FISHERIES': frozenset({'Agricultural production, crops', 'Agricultural production, livestock', 'Agricultural services, n.e.c.', 'Fishing, hunting, and trapping', 'Forestry', 'Landscape and horticultural services', 'Veterinary services'}),
    'MINING': frozenset({'Coal mining', 'Metal mining', 'Nonmetallic mining and quarrying, except fuels', 'Oil and gas extraction'}),
    'MANUFACTURING': frozenset({'Agricultural chemicals', 'Aircraft and parts', 'Apparel and accessories, except knit', 'Bakery products', 'Beverage industries', 'Blast furnaces, steelworks, rolling and finishing mills', 'Canned, frozen, and preserved fruits and vegetables', 'Carpets and rugs', 'Cement, concrete, gypsum, and plaster products', 'Computers and related equipment', 'Construction and material handling machines', 'Cutlery, handtools, and general hardware', 'Cycles and miscellaneous transportation equipment', 'Dairy products', 'Drugs', 'Dyeing and finishing textiles, except wool and knit goods', 'Electrical machinery, equipment, and supplies, n.e.c.', 'Electrical machinery, equipment, and supplies, n.s.', 'Engines and turbines', 'Fabricated structural metal products', 'Farm machinery and equipment', 'Food industries, n.s.', 'Footwear, except rubber and plastic', 'Furniture and fixtures', 'Glass and glass products', 'Grain mill products', 'Guided missiles, space vehicles, and parts', 'Household appliances', 'Industrial and miscellaneous chemicals', 'Iron and steel foundries', 'Knitting mills', 'Leather products, except footwear', 'Leather tanning and finishing', 'Logging', 'Machinery, except electrical, n.e.c.', 'Machinery, n.s.', 'Manufacturing industries, n.s.', 'Meat products', 'Medical, dental, and optical instruments and supplies', 'Metal forgings and stampings', 'Metal industries, n.s.', 'Metalworking machinery', 'Misc. food preparations and kindred products', 'Misc. nonmetallic mineral and stone products', 'Miscellaneous fabricated metal products', 'Miscellaneous fabricated textile products', 'Miscellaneous manufacturing industries', 'Miscellaneous paper and pulp products', 'Miscellaneous petroleum and coal products', 'Miscellaneous plastics products', 'Miscellaneous textile mill products', 'Miscellaneous wood products', 'Motor vehicles and motor vehicle equipment', 'Newspaper publishing and printing', 'Office and accounting machines', 'Ordnance', 'Other primary metal industries', 'Other rubber products, and plastics footwear and belting', 'Paints, varnishes, and related products', 'Paperboard containers and boxes', 'Petroleum refining', 'Photographic equipment and supplies', 'Plastics, synthetics, and resins', 'Pottery and related products', 'Primary aluminum industries', 'Printing, publishing, and allied industries, except newspapers', 'Pulp, paper, and paperboard mills', 'Radio, TV, and communication equipment', 'Railroad locomotives and equipment', 'Sawmills, planing mills, and millwork', 'Scientific and controlling instruments', 'Screw machine products', 'Ship and boat building and repairing', 'Soaps and cosmetics', 'Structural clay products', 'Sugar and confectionery products', 'Tires and inner tubes', 'Tobacco manufactures', 'Toys, amusement, and sporting goods', 'Watches, clocks, and clockwork operated devices', 'Wood buildings and mobile homes', 'Yarn, thread, and fabric mills'}),
    'Nondurable Goods': frozenset({'Agricultural chemicals', 'Apparel and accessories, except knit', 'Bakery products', 'Beverage industries', 'Canned, frozen, and preserved fruits and vegetables', 'Carpets and rugs', 'Dairy products', 'Drugs', 'Dyeing and finishing textiles, except wool and knit goods', 'Food industries, n.s.', 'Footwear, except rubber and plastic', 'Grain mill products', 'Industrial and miscellaneous chemicals', 'Knitting mills', 'Leather products, except footwear', 'Leather tanning and finishing', 'Meat products', 'Misc. food preparations and kindred products', 'Miscellaneous fabricated textile products', 'Miscellaneous paper and pulp products', 'Miscellaneous petroleum and coal products', 'Miscellaneous plastics products', 'Miscellaneous textile mill products', 'Newspaper publishing and printing', 'Other rubber products, and plastics footwear and belting', 'Paints, varnishes, and related products', 'Paperboard containers and boxes', 'Petroleum refining', 'Plastics, synthetics, and resins', 'Printing, publishing, and allied industries, except newspapers', 'Pulp, paper, and paperboard mills', 'Soaps and cosmetics', 'Sugar and confectionery products', 'Tires and inner tubes', 'Tobacco manufactures', 'Yarn, thread, and fabric mills'}),
    'Food and kindred products': frozenset({'Bakery products', 'Beverage industries', 'Canned, frozen, and preserved fruits and vegetables', 'Dairy products', 'Food industries, n.s.', 'Grain mill products', 'Meat products', 'Misc. food preparations and kindred products', 'Sugar and confectionery products'}),
    'Textile mill products': frozenset({'Carpets and rugs', 'Dyeing and finishing textiles, except wool and knit goods', 'Knitting mills', 'Miscellaneous textile mill products', 'Yarn, thread, and fabric mills'}),
    'Paper and allied products': frozenset({'Miscellaneous paper and pulp products', 'Paperboard containers and boxes', 'Pulp, paper, and paperboard mills'}),
    'Printing, publishing, and allied industries': frozenset({'Newspaper publishing and printing', 'Printing, publishing, and allied industries, except newspapers'}),
    'Chemicals and allied products': frozenset({'Agricultural chemicals', 'Drugs', 'Industrial and miscellaneous chemicals', 'Paints, varnishes, and related products', 'Plastics, synthetics, and resins', 'Soaps and cosmetics'}),
    'Petroleum and coal products': frozenset({'Miscellaneous petroleum and coal products', 'Petroleum refining'}),
    'Rubber and miscellaneous plastics products': frozenset({'Miscellaneous plastics products', 'Other rubber products, and plastics footwear and belting', 'Tires and inner tubes'}),
    'Leather and leather products': frozenset({'Footwear, except rubber and plastic', 'Leather products, except footwear', 'Leather tanning and finishing'}),
    'Durable Goods': frozenset({'Aircraft and parts', 'Blast furnaces, steelworks, rolling and finishing mills', 'Cement, concrete, gypsum, and plaster products', 'Computers and related equipment', 'Construction and material handling machines', 'Cutlery, handtools, and general hardware', 'Cycles and miscellaneous transportation equipment', 'Electrical machinery, equipment, and supplies, n.e.c.', 'Electrical machinery, equipment, and supplies, n.s.', 'Engines and turbines', 'Fabricated structural metal products', 'Farm machinery and equipment', 'Furniture and fixtures', 'Glass and glass products', 'Guided missiles, space vehicles, and parts', 'Household appliances', 'Iron and steel foundries', 'Logging', 'Machinery, except electrical, n.e.c.', 'Machinery, n.s.', 'Manufacturing industries, n.s.', 'Medical, dental, and optical instruments and supplies', 'Metal forgings and stampings', 'Metal industries, n.s.', 'Metalworking machinery', 'Misc. nonmetallic mineral and stone products', 'Miscellaneous fabricated metal products', 'Miscellaneous manufacturing industries', 'Miscellaneous wood products', 'Motor vehicles and motor vehicle equipment', 'Office and accounting machines', 'Ordnance', 'Other primary metal industries', 'Photographic equipment and supplies', 'Pottery and related products', 'Primary aluminum industries', 'Radio, TV, and communication equipment', 'Railroad locomotives and equipment', 'Sawmills, planing mills, and millwork', 'Scientific and controlling instruments', 'Screw machine products', 'Ship and boat building and repairing', 'Structural clay products', 'Toys, amusement, and sporting goods', 'Watches, clocks, and clockwork operated devices', 'Wood buildings and mobile homes'}),
    'Lumber and woods products, except furniture': frozenset({'Logging', 'Miscellaneous wood products', 'Sawmills, planing mills, and millwork', 'Wood buildings and mobile homes'}),
    'Stone, clay, glass and concrete products': frozenset({'Cement, concrete, gypsum, and plaster products', 'Glass and glass products', 'Misc. nonmetallic mineral and stone products', 'Pottery and related products', 'Structural clay products'}),
    'Metal industries': frozenset({'Blast furnaces, steelworks, rolling and finishing mills', 'Cutlery, handtools, and general hardware', 'Fabricated structural metal products', 'Iron and steel foundries', 'Metal forgings and stampings', 'Metal industries, n.s.', 'Miscellaneous fabricated metal products', 'Ordnance', 'Other primary metal industries', 'Primary aluminum industries', 'Screw machine products'}),
    'Machinery and computing equipment': frozenset({'Computers and related equipment', 'Construction and material handling machines', 'Engines and turbines', 'Farm machinery and equipment', 'Machinery, except electrical, n.e.c.', 'Machinery, n.s.', 'Metalworking machinery', 'Office and accounting machines'}),
    'Electrical machinery, equipment, and supplies': frozenset({'Electrical machinery, equipment, and supplies, n.e.c.', 'Electrical machinery, equipment, and supplies, n.s.', 'Household appliances', 'Radio, TV, and communication equipment'}),
    'Transportation equipment': frozenset({'Aircraft and parts', 'Cycles and miscellaneous transportation equipment', 'Guided missiles, space vehicles, and parts', 'Motor vehicles and motor vehicle equipment', 'Railroad locomotives and equipment', 'Ship and boat building and repairing'}),
    'Professional and photographic equipment, and watches': frozenset({'Medical, dental, and optical instruments and supplies', 'Photographic equipment and supplies', 'Scientific and controlling instruments', 'Watches, clocks, and clockwork operated devices'}),
    'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES': frozenset({'Air transportation', 'Bus service and urban transit', 'Electric and gas, and other combinations', 'Electric light and power', 'Gas and steam supply systems', 'Pipe lines, except natural gas', 'Radio and television broadcasting and cable', 'Railroads', 'Sanitary services', 'Services incidental to transportation', 'Taxicab service', 'Telegraph and miscellaneous communications services', 'Trucking service', 'U.S. Postal Service', 'Utilities, n.s.', 'Warehousing and storage', 'Water supply and irrigation', 'Water transportation', 'Wired communications'}),
    'Transportation': frozenset({'Air transportation', 'Bus service and urban transit', 'Pipe lines, except natural gas', 'Railroads', 'Services incidental to transportation', 'Taxicab service', 'Trucking service', 'U.S. Postal Service', 'Warehousing and storage', 'Water transportation'}),
    'Communications': frozenset({'Radio and television broadcasting and cable', 'Telegraph and miscellaneous communications services', 'Wired communications'}),
    'Utilities and sanitary services': frozenset({'Electric and gas, and other combinations', 'Electric light and power', 'Gas and steam supply systems', 'Sanitary services', 'Utilities, n.s.', 'Water supply and irrigation'}),
    'WHOLESALE TRADE': frozenset({'Alcoholic beverages', 'Apparel, fabrics, and notions', 'Drugs, chemicals, and allied products', 'Electrical goods', 'Farm supplies', 'Farm-product raw materials', 'Furniture and home furnishings', 'Groceries and related products', 'Hardware, plumbing and heating supplies', 'Lumber and construction materials', 'Machinery, equipment, and supplies', 'Metals and minerals, except petroleum', 'Miscellaneous wholesale, durable goods', 'Miscellaneous wholesale, nondurable goods', 'Motor vehicles and equipment', 'Paper and paper products', 'Petroleum products', 'Professional and commercial equipment and supplies', 'Scrap and waste materials', 'Wholesale trade, n.s.'}),
    'Durable Goods': frozenset({'Electrical goods', 'Furniture and home furnishings', 'Hardware, plumbing and heating supplies', 'Lumber and construction materials', 'Machinery, equipment, and supplies', 'Metals and minerals, except petroleum', 'Miscellaneous wholesale, durable goods', 'Motor vehicles and equipment', 'Professional and commercial equipment and supplies', 'Scrap and waste materials'}),
    'Nondurable Goods': frozenset({'Alcoholic beverages', 'Apparel, fabrics, and notions', 'Drugs, chemicals, and allied products', 'Farm supplies', 'Farm-product raw materials', 'Groceries and related products', 'Miscellaneous wholesale, nondurable goods', 'Paper and paper products', 'Petroleum products', 'Wholesale trade, n.s.'}),
    'RETAIL TRADE': frozenset({'Apparel and accessory stores, except shoe', 'Auto and home supply stores', 'Book and stationery stores', 'Catalog and mail order houses', 'Dairy products stores', 'Department stores', 'Direct selling establishments', 'Drug stores', 'Eating and drinking places', 'Food stores, n.e.c.', 'Fuel dealers', 'Furniture and home furnishings stores', 'Gasoline service stations', 'Gift, novelty, and souvenir shops', 'Grocery stores', 'Hardware stores', 'Household appliance stores', 'Jewelry stores', 'Liquor stores', 'Lumber and building material retailing', 'Miscellaneous general merchandise stores', 'Miscellaneous retail stores', 'Miscellaneous vehicle dealers', 'Mobile home dealers', 'Motor vehicle dealers', 'Music stores', 'Radio, TV, and computer stores', 'Retail bakeries', 'Retail florists', 'Retail nurseries and garden stores', 'Retail trade, n.s.', 'Sewing, needlework, and piece goods stores', 'Shoe stores', 'Sporting goods, bicycles, and hobby stores', 'Variety stores', 'Vending machine operators'}),
    'FINANCE, INSURANCE, AND REAL ESTATE': frozenset({'Banking', 'Credit agencies, n.e.c.', 'Insurance', 'Real estate, including real estate-insurance offices', 'Savings institutions, including credit unions', 'Security, commodity brokerage, and investment companies'}),
    'BUSINESS AND REPAIR SERVICES': frozenset({'Advertising', 'Automobile parking and carwashes', 'Automotive rental and leasing, without drivers', 'Automotive repair and related services', 'Business services, n.e.c.', 'Computer and data processing services', 'Detective and protective services', 'Electrical repair shops', 'Miscellaneous repair services', 'Personnel supply services', 'Services to dwellings and other buildings'}),
    'PERSONAL SERVICES': frozenset({'Barber shops', 'Beauty shops', 'Dressmaking shops', 'Funeral service and crematories', 'Hotels and motels', 'Laundry, cleaning, and garment services', 'Lodging places, except hotels and motels', 'Miscellaneous personal services', 'Private households', 'Shoe repair shops'}),
    'ENTERTAINMENT AND RECREATION SERVICES': frozenset({'Bowling centers', 'Miscellaneous entertainment and recreation services', 'Theaters and motion pictures', 'Video tape rental'}),
    'PROFESSIONAL AND RELATED SERVICES': frozenset({'Accounting, auditing, and bookkeeping services', 'Child day care services', 'Colleges and universities', 'Educational services, n.e.c.', 'Elementary and secondary schools', 'Engineering, architectural, and surveying services', 'Family child care homes', 'Health services, n.e.c.', 'Hospitals', 'Job training and vocational rehabilitation services', 'Labor unions', 'Legal services', 'Libraries', 'Management and public relations services', 'Membership organizations, n.e.c.', 'Miscellaneous professional and related services', 'Museums, art galleries, and zoos', 'Nursing and personal care facilities', 'Offices and clinics of chiropractors', 'Offices and clinics of dentists', 'Offices and clinics of health practitioners, n.e.c.', 'Offices and clinics of optometrists', 'Offices and clinics of physicians', 'Religious organizations', 'Research, development, and testing services', 'Residential care facilities, without nursing', 'Social services, n.e.c.', 'Vocational schools'}),
    'PUBLIC ADMINISTRATION': frozenset({'Administration of economic programs', 'Administration of environmental quality and housing programs', 'Administration of human resources programs', 'Executive and legislative offices', 'General government, n.e.c.', 'Justice, public order, and safety', 'National security and international affairs', 'Public finance, taxation, and monetary policy'}),
    # The following four categories have no more than one subindustry in the data.
    'CONSTRUCTION': frozenset({'All construction'}),
    'Apparel and other finished textile products': frozenset({'Apparel and accessories, except knit', 'Miscellaneous fabricated textile products'}),
    #'ACTIVE DUTY MILITARY': frozenset({'Air Force', 'Armed Forces, branch not specified', 'Army', 'Coast Guard', 'Marines', 'Military Reserves or National Guard',  'Navy'}),
    # Remove the above group because it would be double redundant
    'Armed Forces': frozenset({'Air Force', 'Armed Forces, branch not specified', 'Army', 'Coast Guard', 'Marines', 'Military Reserves or National Guard', 'Navy'})
    }

singularIndustryGroups = ['CONSTRUCTION', 'Apparel and other finished textile products','Armed Forces']

REDUNDANTINDUSTRIES = list(set.union(set(),*[INDUSTRYGROUPS[k] for k in singularIndustryGroups]))


#%% Now use this code to computer the inverse as well
'''
INDUSTRYGROUPMAP = defaultdict(set)
for group,industries in INDUSTRYGROUPS.items():
    for ind in industries:
        INDUSTRYGROUPMAP[ind].add(group)

for k,v in INDUSTRYGROUPMAP.items():
    INDUSTRYGROUPMAP[k] = tuple(v)
'''



# %% and hardcode it

INDUSTRYGROUPMAP = {
    'Agricultural services, n.e.c.': ('AGRICULTURE, FORESTRY, AND FISHERIES',),
    'Forestry': ('AGRICULTURE, FORESTRY, AND FISHERIES',),
    'Veterinary services': ('AGRICULTURE, FORESTRY, AND FISHERIES',),
    'Landscape and horticultural services': ('AGRICULTURE, FORESTRY, AND FISHERIES',),
    'Fishing, hunting, and trapping': ('AGRICULTURE, FORESTRY, AND FISHERIES',),
    'Agricultural production, livestock': ('AGRICULTURE, FORESTRY, AND FISHERIES',),
    'Agricultural production, crops': ('AGRICULTURE, FORESTRY, AND FISHERIES',),
    'Coal mining': ('MINING',),
    'Nonmetallic mining and quarrying, except fuels': ('MINING',),
    'Metal mining': ('MINING',),
    'Oil and gas extraction': ('MINING',),
    'Fabricated structural metal products': ('Metal industries', 'MANUFACTURING'),
    'Leather products, except footwear': ('Leather and leather products', 'MANUFACTURING'),
    'Metal industries, n.s.': ('Metal industries', 'MANUFACTURING'),
    'Industrial and miscellaneous chemicals': ('Chemicals and allied products', 'MANUFACTURING'),
    'Miscellaneous textile mill products': ('Textile mill products', 'MANUFACTURING'),
    'Other rubber products, and plastics footwear and belting': ('Rubber and miscellaneous plastics products', 'MANUFACTURING'),
    'Machinery, except electrical, n.e.c.': ('Machinery and computing equipment', 'MANUFACTURING'),
    'Paints, varnishes, and related products': ('Chemicals and allied products', 'MANUFACTURING'),
    'Misc. food preparations and kindred products': ('Food and kindred products', 'MANUFACTURING'),
    'Tires and inner tubes': ('Rubber and miscellaneous plastics products', 'MANUFACTURING'),
    'Cycles and miscellaneous transportation equipment': ('Transportation equipment', 'MANUFACTURING'),
    'Food industries, n.s.': ('Food and kindred products', 'MANUFACTURING'),
    'Miscellaneous wood products': ('Lumber and woods products, except furniture', 'MANUFACTURING'),
    'Petroleum refining': ('Petroleum and coal products', 'MANUFACTURING'),
    'Medical, dental, and optical instruments and supplies': ('Professional and photographic equipment, and watches', 'MANUFACTURING'),
    'Miscellaneous fabricated textile products': ('Apparel and other finished textile products', 'MANUFACTURING'),
    'Watches, clocks, and clockwork operated devices': ('Professional and photographic equipment, and watches', 'MANUFACTURING'),
    'Agricultural chemicals': ('Chemicals and allied products', 'MANUFACTURING'),
    'Miscellaneous plastics products': ('Rubber and miscellaneous plastics products', 'MANUFACTURING'),
    'Knitting mills': ('Textile mill products', 'MANUFACTURING'),
    'Soaps and cosmetics': ('Chemicals and allied products', 'MANUFACTURING'),
    'Office and accounting machines': ('Machinery and computing equipment', 'MANUFACTURING'),
    'Aircraft and parts': ('Transportation equipment', 'MANUFACTURING'),
    'Yarn, thread, and fabric mills': ('Textile mill products', 'MANUFACTURING'),
    'Guided missiles, space vehicles, and parts': ('Transportation equipment', 'MANUFACTURING'),
    'Cutlery, handtools, and general hardware': ('Metal industries', 'MANUFACTURING'),
    'Ordnance': ('Metal industries', 'MANUFACTURING'),
    'Household appliances': ('Electrical machinery, equipment, and supplies', 'MANUFACTURING'),
    'Electrical machinery, equipment, and supplies, n.s.': ('Electrical machinery, equipment, and supplies', 'MANUFACTURING'),
    'Pulp, paper, and paperboard mills': ('Paper and allied products', 'MANUFACTURING'),
    'Misc. nonmetallic mineral and stone products': ('Stone, clay, glass and concrete products', 'MANUFACTURING'),
    'Newspaper publishing and printing': ('Printing, publishing, and allied industries', 'MANUFACTURING'),
    'Structural clay products': ('Stone, clay, glass and concrete products', 'MANUFACTURING'),
    'Primary aluminum industries': ('Metal industries', 'MANUFACTURING'),
    'Wood buildings and mobile homes': ('Lumber and woods products, except furniture', 'MANUFACTURING'),
    'Electrical machinery, equipment, and supplies, n.e.c.': ('Electrical machinery, equipment, and supplies', 'MANUFACTURING'),
    'Sawmills, planing mills, and millwork': ('Lumber and woods products, except furniture', 'MANUFACTURING'),
    'Miscellaneous paper and pulp products': ('Paper and allied products', 'MANUFACTURING'),
    'Canned, frozen, and preserved fruits and vegetables': ('Food and kindred products', 'MANUFACTURING'),
    'Beverage industries': ('Food and kindred products', 'MANUFACTURING'),
    'Sugar and confectionery products': ('Food and kindred products', 'MANUFACTURING'),
    'Furniture and fixtures': ('MANUFACTURING',),
    'Cement, concrete, gypsum, and plaster products': ('Stone, clay, glass and concrete products', 'MANUFACTURING'),
    'Glass and glass products': ('Stone, clay, glass and concrete products', 'MANUFACTURING'),
    'Metalworking machinery': ('Machinery and computing equipment', 'MANUFACTURING'),
    'Carpets and rugs': ('Textile mill products', 'MANUFACTURING'),
    'Scientific and controlling instruments': ('Professional and photographic equipment, and watches', 'MANUFACTURING'),
    'Paperboard containers and boxes': ('Paper and allied products', 'MANUFACTURING'),
    'Motor vehicles and motor vehicle equipment': ('Transportation equipment', 'MANUFACTURING'),
    'Construction and material handling machines': ('Machinery and computing equipment', 'MANUFACTURING'),
    'Screw machine products': ('Metal industries', 'MANUFACTURING'),
    'Meat products': ('Food and kindred products', 'MANUFACTURING'),
    'Computers and related equipment': ('Machinery and computing equipment', 'MANUFACTURING'),
    'Ship and boat building and repairing': ('Transportation equipment', 'MANUFACTURING'),
    'Plastics, synthetics, and resins': ('Chemicals and allied products', 'MANUFACTURING'),
    'Miscellaneous petroleum and coal products': ('Petroleum and coal products', 'MANUFACTURING'),
    'Footwear, except rubber and plastic': ('Leather and leather products', 'MANUFACTURING'),
    'Drugs': ('Chemicals and allied products', 'MANUFACTURING'),
    'Logging': ('Lumber and woods products, except furniture', 'MANUFACTURING'),
    'Grain mill products': ('Food and kindred products', 'MANUFACTURING'),
    'Iron and steel foundries': ('Metal industries', 'MANUFACTURING'),
    'Dyeing and finishing textiles, except wool and knit goods': ('Textile mill products', 'MANUFACTURING'),
    'Farm machinery and equipment': ('Machinery and computing equipment', 'MANUFACTURING'),
    'Metal forgings and stampings': ('Metal industries', 'MANUFACTURING'),
    'Printing, publishing, and allied industries, except newspapers': ('Printing, publishing, and allied industries', 'MANUFACTURING'),
    'Photographic equipment and supplies': ('Professional and photographic equipment, and watches', 'MANUFACTURING'),
    'Blast furnaces, steelworks, rolling and finishing mills': ('Metal industries', 'MANUFACTURING'),
    'Other primary metal industries': ('Metal industries', 'MANUFACTURING'),
    'Leather tanning and finishing': ('Leather and leather products', 'MANUFACTURING'),
    'Miscellaneous fabricated metal products': ('Metal industries', 'MANUFACTURING'),
    'Engines and turbines': ('Machinery and computing equipment', 'MANUFACTURING'),
    'Railroad locomotives and equipment': ('Transportation equipment', 'MANUFACTURING'),
    'Pottery and related products': ('Stone, clay, glass and concrete products', 'MANUFACTURING'),
    'Dairy products': ('Food and kindred products', 'MANUFACTURING'),
    'Manufacturing industries, n.s.': ('MANUFACTURING',),
    'Miscellaneous manufacturing industries': ('MANUFACTURING',),
    'Tobacco manufactures': ('MANUFACTURING',),
    'Apparel and accessories, except knit': ('Apparel and other finished textile products', 'MANUFACTURING'),
    'Toys, amusement, and sporting goods': ('MANUFACTURING',),
    'Machinery, n.s.': ('Machinery and computing equipment', 'MANUFACTURING'),
    'Radio, TV, and communication equipment': ('Electrical machinery, equipment, and supplies', 'MANUFACTURING'),
    'Bakery products': ('Food and kindred products', 'MANUFACTURING'),
    'Farm supplies': ('WHOLESALE TRADE', 'Nondurable Goods'),
    'Miscellaneous wholesale, nondurable goods': ('WHOLESALE TRADE', 'Nondurable Goods'),
    'Apparel, fabrics, and notions': ('WHOLESALE TRADE', 'Nondurable Goods'),
    'Paper and paper products': ('WHOLESALE TRADE', 'Nondurable Goods'),
    'Wholesale trade, n.s.': ('WHOLESALE TRADE', 'Nondurable Goods'),
    'Alcoholic beverages': ('WHOLESALE TRADE', 'Nondurable Goods'),
    'Petroleum products': ('WHOLESALE TRADE', 'Nondurable Goods'),
    'Farm-product raw materials': ('WHOLESALE TRADE', 'Nondurable Goods'),
    'Drugs, chemicals, and allied products': ('WHOLESALE TRADE', 'Nondurable Goods'),
    'Groceries and related products': ('WHOLESALE TRADE', 'Nondurable Goods'),
    'Metals and minerals, except petroleum': ('Durable Goods', 'WHOLESALE TRADE'),
    'Motor vehicles and equipment': ('Durable Goods', 'WHOLESALE TRADE'),
    'Professional and commercial equipment and supplies': ('Durable Goods', 'WHOLESALE TRADE'),
    'Scrap and waste materials': ('Durable Goods', 'WHOLESALE TRADE'),
    'Machinery, equipment, and supplies': ('Durable Goods', 'WHOLESALE TRADE'),
    'Miscellaneous wholesale, durable goods': ('Durable Goods', 'WHOLESALE TRADE'),
    'Lumber and construction materials': ('Durable Goods', 'WHOLESALE TRADE'),
    'Hardware, plumbing and heating supplies': ('Durable Goods', 'WHOLESALE TRADE'),
    'Furniture and home furnishings': ('Durable Goods', 'WHOLESALE TRADE'),
    'Electrical goods': ('Durable Goods', 'WHOLESALE TRADE'),
    'Electric and gas, and other combinations': ('Utilities and sanitary services', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Railroads': ('Transportation', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'U.S. Postal Service': ('Transportation', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Water supply and irrigation': ('Utilities and sanitary services', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Utilities, n.s.': ('Utilities and sanitary services', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Taxicab service': ('Transportation', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Water transportation': ('Transportation', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Bus service and urban transit': ('Transportation', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Radio and television broadcasting and cable': ('Communications', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Air transportation': ('Transportation', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Electric light and power': ('Utilities and sanitary services', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Services incidental to transportation': ('Transportation', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Sanitary services': ('Utilities and sanitary services', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Warehousing and storage': ('Transportation', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Telegraph and miscellaneous communications services': ('Communications', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Pipe lines, except natural gas': ('Transportation', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Trucking service': ('Transportation', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Wired communications': ('Communications', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Gas and steam supply systems': ('Utilities and sanitary services', 'TRANSPORTATION, COMMUNICATIONS, AND OTHER PUBLIC UTILITIES'),
    'Retail bakeries': ('RETAIL TRADE',),
    'Radio, TV, and computer stores': ('RETAIL TRADE',),
    'Household appliance stores': ('RETAIL TRADE',),
    'Variety stores': ('RETAIL TRADE',),
    'Auto and home supply stores': ('RETAIL TRADE',),
    'Book and stationery stores': ('RETAIL TRADE',),
    'Food stores, n.e.c.': ('RETAIL TRADE',),
    'Miscellaneous retail stores': ('RETAIL TRADE',),
    'Vending machine operators': ('RETAIL TRADE',),
    'Grocery stores': ('RETAIL TRADE',),
    'Dairy products stores': ('RETAIL TRADE',),
    'Lumber and building material retailing': ('RETAIL TRADE',),
    'Hardware stores': ('RETAIL TRADE',),
    'Jewelry stores': ('RETAIL TRADE',),
    'Sporting goods, bicycles, and hobby stores': ('RETAIL TRADE',),
    'Miscellaneous general merchandise stores': ('RETAIL TRADE',),
    'Music stores': ('RETAIL TRADE',),
    'Liquor stores': ('RETAIL TRADE',),
    'Direct selling establishments': ('RETAIL TRADE',),
    'Motor vehicle dealers': ('RETAIL TRADE',),
    'Drug stores': ('RETAIL TRADE',),
    'Fuel dealers': ('RETAIL TRADE',),
    'Retail trade, n.s.': ('RETAIL TRADE',),
    'Gasoline service stations': ('RETAIL TRADE',),
    'Sewing, needlework, and piece goods stores': ('RETAIL TRADE',),
    'Gift, novelty, and souvenir shops': ('RETAIL TRADE',),
    'Catalog and mail order houses': ('RETAIL TRADE',),
    'Retail nurseries and garden stores': ('RETAIL TRADE',),
    'Shoe stores': ('RETAIL TRADE',),
    'Furniture and home furnishings stores': ('RETAIL TRADE',),
    'Eating and drinking places': ('RETAIL TRADE',),
    'Apparel and accessory stores, except shoe': ('RETAIL TRADE',),
    'Mobile home dealers': ('RETAIL TRADE',),
    'Department stores': ('RETAIL TRADE',),
    'Miscellaneous vehicle dealers': ('RETAIL TRADE',),
    'Retail florists': ('RETAIL TRADE',),
    'Credit agencies, n.e.c.': ('FINANCE, INSURANCE, AND REAL ESTATE',),
    'Savings institutions, including credit unions': ('FINANCE, INSURANCE, AND REAL ESTATE',),
    'Security, commodity brokerage, and investment companies': ('FINANCE, INSURANCE, AND REAL ESTATE',),
    'Insurance': ('FINANCE, INSURANCE, AND REAL ESTATE',),
    'Banking': ('FINANCE, INSURANCE, AND REAL ESTATE',),
    'Real estate, including real estate-insurance offices': ('FINANCE, INSURANCE, AND REAL ESTATE',),
    'Business services, n.e.c.': ('BUSINESS AND REPAIR SERVICES',),
    'Miscellaneous repair services': ('BUSINESS AND REPAIR SERVICES',),
    'Services to dwellings and other buildings': ('BUSINESS AND REPAIR SERVICES',),
    'Automotive rental and leasing, without drivers': ('BUSINESS AND REPAIR SERVICES',),
    'Personnel supply services': ('BUSINESS AND REPAIR SERVICES',),
    'Advertising': ('BUSINESS AND REPAIR SERVICES',),
    'Electrical repair shops': ('BUSINESS AND REPAIR SERVICES',),
    'Automobile parking and carwashes': ('BUSINESS AND REPAIR SERVICES',),
    'Automotive repair and related services': ('BUSINESS AND REPAIR SERVICES',),
    'Computer and data processing services': ('BUSINESS AND REPAIR SERVICES',),
    'Detective and protective services': ('BUSINESS AND REPAIR SERVICES',),
    'Laundry, cleaning, and garment services': ('PERSONAL SERVICES',),
    'Shoe repair shops': ('PERSONAL SERVICES',),
    'Dressmaking shops': ('PERSONAL SERVICES',),
    'Hotels and motels': ('PERSONAL SERVICES',),
    'Lodging places, except hotels and motels': ('PERSONAL SERVICES',),
    'Funeral service and crematories': ('PERSONAL SERVICES',),
    'Private households': ('PERSONAL SERVICES',),
    'Beauty shops': ('PERSONAL SERVICES',),
    'Barber shops': ('PERSONAL SERVICES',),
    'Miscellaneous personal services': ('PERSONAL SERVICES',),
    'Miscellaneous entertainment and recreation services': ('ENTERTAINMENT AND RECREATION SERVICES',),
    'Theaters and motion pictures': ('ENTERTAINMENT AND RECREATION SERVICES',),
    'Video tape rental': ('ENTERTAINMENT AND RECREATION SERVICES',),
    'Bowling centers': ('ENTERTAINMENT AND RECREATION SERVICES',),
    'Offices and clinics of dentists': ('PROFESSIONAL AND RELATED SERVICES',),
    'Educational services, n.e.c.': ('PROFESSIONAL AND RELATED SERVICES',),
    'Museums, art galleries, and zoos': ('PROFESSIONAL AND RELATED SERVICES',),
    'Miscellaneous professional and related services': ('PROFESSIONAL AND RELATED SERVICES',),
    'Job training and vocational rehabilitation services': ('PROFESSIONAL AND RELATED SERVICES',),
    'Offices and clinics of chiropractors': ('PROFESSIONAL AND RELATED SERVICES',),
    'Religious organizations': ('PROFESSIONAL AND RELATED SERVICES',),
    'Family child care homes': ('PROFESSIONAL AND RELATED SERVICES',),
    'Membership organizations, n.e.c.': ('PROFESSIONAL AND RELATED SERVICES',),
    'Research, development, and testing services': ('PROFESSIONAL AND RELATED SERVICES',),
    'Colleges and universities': ('PROFESSIONAL AND RELATED SERVICES',),
    'Accounting, auditing, and bookkeeping services': ('PROFESSIONAL AND RELATED SERVICES',),
    'Health services, n.e.c.': ('PROFESSIONAL AND RELATED SERVICES',),
    'Social services, n.e.c.': ('PROFESSIONAL AND RELATED SERVICES',),
    'Offices and clinics of health practitioners, n.e.c.': ('PROFESSIONAL AND RELATED SERVICES',),
    'Offices and clinics of optometrists': ('PROFESSIONAL AND RELATED SERVICES',),
    'Management and public relations services': ('PROFESSIONAL AND RELATED SERVICES',),
    'Elementary and secondary schools': ('PROFESSIONAL AND RELATED SERVICES',),
    'Offices and clinics of physicians': ('PROFESSIONAL AND RELATED SERVICES',),
    'Residential care facilities, without nursing': ('PROFESSIONAL AND RELATED SERVICES',),
    'Vocational schools': ('PROFESSIONAL AND RELATED SERVICES',),
    'Hospitals': ('PROFESSIONAL AND RELATED SERVICES',),
    'Libraries': ('PROFESSIONAL AND RELATED SERVICES',),
    'Nursing and personal care facilities': ('PROFESSIONAL AND RELATED SERVICES',),
    'Engineering, architectural, and surveying services': ('PROFESSIONAL AND RELATED SERVICES',),
    'Child day care services': ('PROFESSIONAL AND RELATED SERVICES',),
    'Labor unions': ('PROFESSIONAL AND RELATED SERVICES',),
    'Legal services': ('PROFESSIONAL AND RELATED SERVICES',),
    'Administration of environmental quality and housing programs': ('PUBLIC ADMINISTRATION',),
    'Administration of economic programs': ('PUBLIC ADMINISTRATION',),
    'Executive and legislative offices': ('PUBLIC ADMINISTRATION',),
    'Justice, public order, and safety': ('PUBLIC ADMINISTRATION',),
    'Administration of human resources programs': ('PUBLIC ADMINISTRATION',),
    'Public finance, taxation, and monetary policy': ('PUBLIC ADMINISTRATION',),
    'National security and international affairs': ('PUBLIC ADMINISTRATION',),
    'General government, n.e.c.': ('PUBLIC ADMINISTRATION',),
    'All construction': ('CONSTRUCTION',),
    'Coast Guard': ('Armed Forces',),
    'Armed Forces, branch not specified': ('Armed Forces',),
    'Navy': ('Armed Forces',),
    'Air Force': ('Armed Forces',),
    'Army': ('Armed Forces',),
    'Marines': ('Armed Forces',),
    'Military Reserves or National Guard': ('Armed Forces',)
}

# %%
